service: auth-server


provider:
 name: aws
 runtime: nodejs18.x #may need same version of node.js --version 20.17.0
 region: us-east-1 # AWS region
 timeout: 30
 environment:
   CLIENT_ID: ${file(config.json):CLIENT_ID}
   CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
   CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
          cors: true  # ✅ add this
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors: true  # ✅ add this
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
          cors: true  # ✅ add this
  sendContactEmail: #Adding serverless function to handle contact form in portfolio-website
    handler: handler.sendContactEmail
    events:
      - http:
          path: contact
          method: post
          cors: true